Databases:
  AISHELL4: aishell4/wav/{uri}.flac
  MSDWILD: msdwild/wav/{uri}.wav

Protocols:
  AISHELL4:
    SpeakerDiarization:
      Custom:
        train:
          uri: aishell4/lists/custom_train.txt
          annotation: aishell4/rttm/{uri}.rttm
          annotated: aishell4/uems/{uri}.uem
        development:
          uri: aishell4/lists/custom_dev.txt
          annotation: aishell4/rttm/{uri}.rttm
          annotated: aishell4/uems/{uri}.uem
        test:
          uri: aishell4/lists/test.txt
          annotation: aishell4/rttm/{uri}.rttm
          annotated: aishell4/uems/{uri}.uem
      Original:
        train:
          uri: aishell4/lists/original_train.txt
          annotation: aishell4/rttm/{uri}.rttm
          annotated: aishell4/uems/{uri}.uem
        test:
          uri: aishell4/lists/test.txt
          annotation: aishell4/rttm/{uri}.rttm
          annotated: aishell4/uems/{uri}.uem
  MSDWILD:
    SpeakerDiarization:
      # Only use "few" data (low speaker count)
      # Splits
      CustomFew:
        train:
          uri: msdwild/lists/custom1_train.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
        development:
          uri: msdwild/lists/custom1_dev.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
        test:
          uri: msdwild/lists/few_train.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
      # uses the "many" subset as test
      CustomManyTest:
        train:
          uri: msdwild/lists/train.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
        development:
          uri: msdwild/lists/dev.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
        test:
          uri: msdwild/lists/test_many.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
      # dubious use of the original subsets, few val is used for development, and many val for test.
      # consider using the "custom" version instead
      Original:
        train:
          uri: msdwild/lists/few_train.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
        development:
          uri: msdwild/lists/few_val.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
        test:
          uri: msdwild/lists/many_val.txt
          annotation: msdwild/rttm/{uri}.rttm
          annotated: msdwild/uems/{uri}.uem
