Databases:
  AISHELL4: wav/{uri}.flac

Protocols:
  AISHELL4:
    SpeakerDiarization:
      Custom:
        train:
          uri: lists/custom_train.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
        development:
          uri: lists/custom_dev.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
        test:
          uri: lists/test.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
      Original:
        train:
          uri: lists/train.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem
        test:
          uri: lists/test.txt
          annotation: rttm/{uri}.rttm
          annotated: uems/{uri}.uem